[general]
live_config_reload = true
import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/keys.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1
blur = true
option_as_alt = "Both"

[window.padding]
x = 0
y = 0

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

