live_config_reload = true

import = ["~/.config/alacritty/mild.toml",]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
option_as_alt = "Both"

[window.padding]
x = 0
y = 0

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

