[colors.primary]
background = "#000000"
foreground = "#dddddd"
dim_foreground = "#aaaaaa"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#1688f0"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#00f955"

[colors.search.matches]
foreground = "#000000"
background = "#fffd00"

[colors.search.focused_match]
foreground = "#000000"
background = "#00f955"

[colors.footer_bar]
foreground = "#000000"
background = "#dddddd"

[colors.hints.start]
foreground = "#000000"
background = "#fffd00"

[colors.hints.end]
foreground = "#000000"
background = "#767676"

[colors.selection]
text = "#000000"
background = "#1688f0"

[colors.normal]
black = "#000000"
red = "#e00606"
green = "#3ed50a"
yellow = "#f1c200"
blue = "#0d73cc"
magenta = "#cb1ed1"
cyan = "#0dcdcd"
white = "#dddddd"

[colors.bright]
black = "#767676"
red = "#ff0043"
green = "#00f955"
yellow = "#fffd00"
blue = "#1a8fff"
magenta = "#fd28ff"
cyan = "#14ffff"
white = "#ffffff"

[colors.dim]
black = "#333333"
red = "#b00505"
green = "#2da307"
yellow = "#bfa000"
blue = "#0a5699"
magenta = "#99179d"
cyan = "#0a9999"
white = "#999999"

[[colors.indexed_colors]]
index = 16
color = "#737387"

[[colors.indexed_colors]]
index = 17
color = "#646487"
