# Path to oh-my-zsh installation.
  export ZSH="/home/abhishek/.oh-my-zsh"
  export TERM="xterm-256color"
#General
 DISABLE_AUTO_TITLE="false"
 ENABLE_CORRECTION="true"
 COMPLETION_WAITING_DOTS="true"

# Powerline
powerline-daemon -q
#. /usr/lib/python3.7/site-packages/powerline/bindings/zsh/powerline.zsh

# Theme
ZSH_THEME="powerlevel9k"

# Plugins
plugins=(
  colored-man-pages
  extract
  fancy-ctrl-z
  fast-syntax-highlighting
  git
  #vi-mode
  z
  zsh-autosuggestions
)


#POWERLEVEL9k
POWERLEVEL9K_MODE='nerdfont-complete'

#Prompt
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator context docker_machine dir vcs time)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs ram load battery)
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{014}╭%F{cyan}"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{014}\u2570%F{cyan}\uf109 %F{001}\uF156%F{001}\ue602%f "

#Segment
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='30'
POWERLEVEL9K_BATTERY_VERBOSE=false
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_CONTEXT_TEMPLATE="\uf489 %n@`hostname -f`"
POWERLEVEL9K_DIR_SHOW_WRITABLE=true
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_VI_COMMAND_MODE_STRING="Normal \ue62b"
POWERLEVEL9K_VI_INSERT_MODE_STRING="Insert \ue52b"
POWERLEVEL9K_TIME_FORMAT="%D{%a,%l:%M %p}"


#Colour
POWERLEVEL9K_COLOR_SCHEME='dark'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='033'
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGED='046'
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='046'
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGING='208'
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='208'
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='black'
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='049'
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND='black'
POWERLEVEL9K_BATTERY_LOW_BACKGROUND='red'
POWERLEVEL9K_BATTERY_LOW_COLOR='red'
POWERLEVEL9K_BATTERY_LOW_FOREGROUND='black'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="196"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="056"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_SSH_BACKGROUND="126"
POWERLEVEL9K_CONTEXT_SSH_FOREGROUND="black"
POWERLEVEL9K_DATE_BACKGROUND="242"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='027'
POWERLEVEL9K_DIR_ETC_BACKGROUND='196'
POWERLEVEL9K_DIR_HOME_BACKGROUND='027'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='027'
POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND='196'
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND='076'
POWERLEVEL9K_LOAD_WARNING_BACKGROUND='214'
POWERLEVEL9K_OS_ICON_FOREGROUND='029'
POWERLEVEL9K_RAM_BACKGROUND="220"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="196"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="black"
POWERLEVEL9K_STATUS_OK_BACKGROUND="040"
POWERLEVEL9K_STATUS_OK_FOREGROUND="black"
POWERLEVEL9K_TIME_BACKGROUND="029"
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='032'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='black'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='red'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='black'

##TODO - zsh internet signal,audacious/pulseaudio now playing

source $ZSH/oh-my-zsh.sh

# Environment
EDITOR=vim 

# Aliases
 alias la="ls -AFb --group-directories-first --sort=extension"
 alias paci="sudo pacman -S"
 alias pacr="sudo pacman -R"
 alias pacu="sudo pacman -Syu"
 alias pp="prettyping --nolegend"

# Commands
