# Path to oh-my-zsh installation.
  export ZSH="/home/abhishek/.oh-my-zsh"

#General
 DISABLE_AUTO_TITLE="false"
 ENABLE_CORRECTION="true"
 COMPLETION_WAITING_DOTS="true"

# Powerline
powerline-daemon -q
#. /usr/lib/python3.7/site-packages/powerline/bindings/zsh/powerline.zsh

# Theme
ZSH_THEME="powerlevel9k"

#POWERLEVEL9k
POWERLEVEL9K_MODE='nerdfont-complete'

#Prompt
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator context docker_machine dir vcs time)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs ram load battery vi_mode)
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{014}╭%F{cyan}"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{014}\u2570%F{cyan}\uf109 %F{001}\uF156%F{001}\ue602%f "

#Segment
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_BATTERY_VERBOSE=false
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3
POWERLEVEL9K_VI_INSERT_MODE_STRING="Insert \ue7c5"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="Normal \ue7c5"
POWERLEVEL9K_CONTEXT_TEMPLATE="\uf489 %n@`hostname -f`"
POWERLEVEL9K_DIR_SHOW_WRITABLE=true
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='30'


#Colour
POWERLEVEL9K_COLOR_SCHEME='dark'
POWERLEVEL9K_TIME_FORMAT="%D{%a,%l:%M %p}"
#POWERLEVEL9K_DATE_FORMAT="%D{}"
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='black'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='black'
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='032'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='red'
POWERLEVEL9K_OS_ICON_FOREGROUND='029'
#POWERLEVEL9K_OS_ICON_BACKGROUND='235'
POWERLEVEL9K_TIME_BACKGROUND="029"
POWERLEVEL9K_DATE_BACKGROUND="242"
#POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
#POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="055"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_SSH_BACKGROUND="126"
POWERLEVEL9K_CONTEXT_SSH_FOREGROUND="black"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="black"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="001"
POWERLEVEL9K_STATUS_OK_BACKGROUND="040"
POWERLEVEL9K_STATUS_OK_FOREGROUND="black"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="black"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="196"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="black"
POWERLEVEL9K_BATTERY_CHARGING='107'
POWERLEVEL9K_BATTERY_CHARGED='blue'
POWERLEVEL9K_BATTERY_LOW_COLOR='red'
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='blue'
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='107'
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='black'
POWERLEVEL9K_BATTERY_LOW_BACKGROUND='red'
POWERLEVEL9K_BATTERY_LOW_FOREGROUND='black'
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND='black'
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='049'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='027'
POWERLEVEL9K_DIR_HOME_BACKGROUND='027'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='027'
POWERLEVEL9K_DIR_ETC_BACKGROUND='196'
POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND='196'

##TODO - zsh internet signal,audacious/pulseaudio now playing


#Color Names 049 

#Example Config
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
#POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="white"
#POWERLEVEL9K_STATUS_VERBOSE=false
#POWERLEVEL9K_TIME_BACKGROUND="black"
#POWERLEVEL9K_TIME_FOREGROUND="249"
#POWERLEVEL9K_TIME_FORMAT="%D{%H:%M} \uE12E"
#POWERLEVEL9K_COLOR_SCHEME='dark'
#POWERLEVEL9K_VCS_GIT_ICON='\uE1AA'
#POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uE1AA'
#POWERLEVEL9K_HIDE_BRANCH_ICON=true


# Plugins
plugins=(
  colored-man-pages
  extract
  fancy-ctrl-z
  fast-syntax-highlighting
  git
  vi-mode
  z
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# Environment
EDITOR=vim 


# Aliases
 alias paci="sudo pacman -S"
 alias pacr="sudo pacman -R"
 alias pacu="sudo pacman -Syu"
 alias la="ls -AFb --group-directories-first --sort=extension"
 alias pp="prettyping --nolegend"
 alias lsc="colorls -A --gs --sd"

